name: ml
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - jupyter
  - scipy
  - h5py
  - tensorflow=2
  - keras
  - pillow
  - librosa
  - nltk
  - openpyxl
  - xlrd
  - tensorflow-datasets
  - hiplot
  - hyperopt
  - gym
